# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ce01d22bbc40a19e54d0afb6b3b59d1a861d255259ca67c32a972146cc60cd3395ffea9b4866f03746dcb7031f97389ef99c7f58c03a94af937e53540fc9bf

test:
  secret_key_base: 3c2b8a223547bb3b5243b8e9041f7bd7244c8fad68626e0712f7034f66102d924506d4c478e259f9abd497fbd0095e4e15372179c7e5fc2359c90fb6485534fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
